PR 1
hsukev/strategy-dola-leverage pull request #1
Opened 2021-06-08 04:25 UTC by plutofeather

The strategy will:

- Deposit any supported token into the respective Anchor market, and receive anToken (cToken) representing deposited collateral in Anchor
- Borrow a different supported token against the collateral, and deposit it into the yVault for that asset.
- Take either a profit or a loss from lending and borrowing on Anchor, and receive earnings from the delegated yVault.
- Earn INV token on Anchor and hold on it as collateral as xINV, rather than selling it for profit.

The rewarded INV (and soon also xINV) will give Yearn voting power on InverseDAO. Inverse will also provide Dola to the strategy in a private market, separate from the public anDola market, in order to increase collateral. Inverse will retain the ability to deposit and withdraw the privately supplied anDola at any time.

2021-06-08 06:51 UTC, 0xKiwi commented on contracts/Strategy.sol
> +        weth.approve(address(this), max);
Is this required?

2021-06-08 16:19 UTC, akshaynexus commented on contracts/Strategy.sol
> +        address[] memory protected = new address[](6);
this should be of length 5,reffering to the protected var entries.

2021-06-11 07:18 UTC, hsukev requested changes

2021-06-11 07:18 UTC, hsukev commented on contracts/Strategy.sol
> +        if (harvestTrigger(_ethToWant(callCostInWei)) || _valueCollateral == 0) {
`harvestTrigger` input should actually be just `callCostInWei`, the `super` method already calls `_ethToWant` so it's enough that we're overriding `_ethToWant`

2021-06-13 03:46 UTC, plutofeather commented on contracts/Strategy.sol
> +        weth.approve(address(this), max);
It is not! Removed.

2021-06-13 03:55 UTC, plutofeather commented on contracts/Strategy.sol
> +        address[] memory protected = new address[](6);
thank you. fixed.

2021-06-20 06:15 UTC, nourharidy commented on contracts/Strategy.sol
> +                uint256 _wantToRepay = router.getAmountsIn(_borrowedToRepay, wantWethPath)[0];
Amount to repay may be vulnerable to flashloan oracle manipulation.

2021-06-20 06:15 UTC, nourharidy commented on contracts/Strategy.sol
> +                        router.swapTokensForExactTokens(_borrowedToRepay, balanceOfWant(), wantWethPath, address(this), now);
why is `amountMinOut` set to `balanceOfWant()`?

2021-06-20 06:15 UTC, nourharidy commented on contracts/Strategy.sol
> +            cWant.redeemUnderlying(_wantRedeemable) == NO_ERROR;
Should this be a `require` statement?

2021-06-20 06:15 UTC, nourharidy commented on contracts/Strategy.sol
> +                router.swapExactTokensForTokens(_actualWithdrawn, 0, path, address(this), now);
How do we guard against frontrunning?

2021-06-20 06:15 UTC, nourharidy commented on contracts/Strategy.sol
> +    function _sellLendingProfits() public {//TODO internal
Why are we not selling?

2021-06-20 06:15 UTC, nourharidy commented on contracts/Strategy.sol
> +        _timelockEscrow.withdraw();
Are the redeemed INVs meant to stay within the strategy?

2021-06-20 06:15 UTC, nourharidy commented on contracts/Strategy.sol
> +        cSupplied.approve(address(this), max);
Do we need these lines?

2021-06-21 00:34 UTC, hsukev commented on contracts/Strategy.sol
> +                router.swapExactTokensForTokens(_rewardsToSell, 0, rewardWantPath, address(this), now);
we use Taichi so tx aren't broadcasted

2021-06-21 00:37 UTC, hsukev commented on contracts/Strategy.sol
> +    function ethToWant(uint256 _amtInWei) public view override returns (uint256){
this is for yearn keeper's use. The keepers calculate whether it's "worth it" depending on gas price and other factors, but the estimation is in eth and need to be converted to whatever token the strategy uses.

2021-06-21 00:41 UTC, hsukev commented on contracts/Strategy.sol
> +    function _sellLendingProfits() public {//TODO internal
should be more appropriately named `_takeLendingProfit`. Is this what you mean?

2021-06-21 00:48 UTC, hsukev commented on contracts/Strategy.sol
> +                        router.swapTokensForExactTokens(_borrowedToRepay, balanceOfWant(), wantWethPath, address(this), now);
the fx is slightly different not the usual `swapExactTokensForTokens`, so the 2nd argument is actually `amountInMax`, the maximum want it could feed in for the trade is the balance it currently has

2021-06-21 00:50 UTC, hsukev commented on contracts/Strategy.sol
> +                router.swapExactTokensForTokens(_actualWithdrawn, 0, path, address(this), now);
same as above, using Taichi should address it

2021-06-21 00:55 UTC, hsukev commented on contracts/Strategy.sol
> +        _timelockEscrow.withdraw();
This is really just for sunset scenarios. On the event of a strategy shut down, the INV will eventually be swept to the yearn treasury, which can be sent to a new strategy when there's migration available

2021-06-21 01:49 UTC, hsukev approved these changes

2021-09-13 04:33 UTC, merged